name: Build

on: [push, pull_request]

jobs:

  build_macos:
    name: macOS
    runs-on: macos-latest
    env:
      # Available versions: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    strategy:
      matrix:
        version: [jdk8u, jdk11u]
        vm: [hotspot]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        brew install bash binutils freetype gnu-sed nasm

    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: 7
      if: matrix.version == 'jdk8u'
        
    - name: Build macOS
      run: |
        export JAVA_HOME=$JAVA_HOME_11_X64
        # Skip freetype build on jdk11+
        if [ ${{ matrix.version }} != "jdk8u" ]; then
          export BUILD_ARGS="--skip-freetype"
        fi
        if [ ${{ matrix.version }} == "jdk8u" ]; then
          export DEVELOPER_DIR="/Applications/Xcode_11.7.app/Contents/Developer"
        fi
        ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: mac
        FILENAME: OpenJDK.tar.gz
        JDK7_BOOT_DIR: ${{ steps.setup-java.outputs.path }}
